/**
 * Markdown formatting module for Deep Research thinking content
 */
import type { BrowseChip, ThinkingContent, ThinkingItem, ThinkingSection } from './types';

/**
 * Format a single thought item as Markdown
 */
function formatThoughtItem(header: string, content: string): string {
  if (!header && !content) {
    return '';
  }

  const parts: string[] = [];

  if (header) {
    parts.push(`### ${header}\n`);
  }

  if (content) {
    parts.push(content);
  }

  return parts.join('\n');
}

/**
 * Format browse chips as Markdown list
 */
function formatBrowseChips(chips: BrowseChip[]): string {
  if (chips.length === 0) {
    return '';
  }

  const lines: string[] = ['#### 研究网站 / Researched Websites\n'];

  chips.forEach((chip) => {
    const title = chip.title ? ` - ${chip.title}` : '';
    lines.push(`- [${chip.domain}](${chip.url})${title}`);
  });

  return lines.join('\n');
}

/**
 * Format a thinking item (either thought or browse chips)
 */
function formatThinkingItem(item: ThinkingItem): string {
  if (item.type === 'thought') {
    return formatThoughtItem(item.header, item.content);
  } else if (item.type === 'browse-chips') {
    return formatBrowseChips(item.chips);
  }
  return '';
}

/**
 * Format a thinking section as Markdown
 */
function formatThinkingSection(section: ThinkingSection, index: number): string {
  const parts: string[] = [];

  // Section header
  parts.push(`## 思考阶段 ${index + 1} / Thinking Phase ${index + 1}\n`);

  // Format items in order
  section.items.forEach((item) => {
    const formatted = formatThinkingItem(item);
    if (formatted) {
      parts.push(formatted);
      parts.push(''); // Add blank line between items
    }
  });

  return parts.join('\n');
}

/**
 * Format timestamp as readable string
 */
function formatTimestamp(isoString: string): string {
  try {
    const date = new Date(isoString);
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    const hours = String(date.getHours()).padStart(2, '0');
    const minutes = String(date.getMinutes()).padStart(2, '0');
    const seconds = String(date.getSeconds()).padStart(2, '0');

    return `${year}-${month}-${day} ${hours}:${minutes}:${seconds}`;
  } catch (error) {
    console.error('[ChatGPT Voyager] Error formatting timestamp:', error);
    return isoString;
  }
}

/**
 * Convert thinking content to Markdown format
 */
export function formatToMarkdown(content: ThinkingContent): string {
  const parts: string[] = [];

  // Title
  parts.push(`# ${content.title}\n`);

  // Metadata
  parts.push(`**导出时间 / Exported At:** ${formatTimestamp(content.exportedAt)}\n`);
  parts.push(`**总思考阶段 / Total Phases:** ${content.sections.length}\n`);
  parts.push('---\n');

  // Format each section
  content.sections.forEach((section, index) => {
    const formatted = formatThinkingSection(section, index);
    if (formatted) {
      parts.push(formatted);
      // Add separator between sections (except for the last one)
      if (index < content.sections.length - 1) {
        parts.push('---\n');
      }
    }
  });

  // Footer
  parts.push('\n---\n');
  parts.push('*Generated by [ChatGPT Voyager](https://github.com/hayashishungenn/chatgpt-voyager)*');

  return parts.join('\n');
}
